// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCclXShkNOvWtqGXd057zUiF7pyExw6Y6E',
    appId: '1:1074170874944:web:08223840c02d819adca3a5',
    messagingSenderId: '1074170874944',
    projectId: 'real-capstone',
    authDomain: 'real-capstone.firebaseapp.com',
    storageBucket: 'real-capstone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT3JF7jAsh0hwH0WxYABZVA--MptslTUg',
    appId: '1:1074170874944:android:0eb0301696e52827dca3a5',
    messagingSenderId: '1074170874944',
    projectId: 'real-capstone',
    storageBucket: 'real-capstone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBisfOfzLYSUX_N62vwKZvqUGkOIJ63JZM',
    appId: '1:1074170874944:ios:b84a7cfd76580a00dca3a5',
    messagingSenderId: '1074170874944',
    projectId: 'real-capstone',
    storageBucket: 'real-capstone.appspot.com',
    iosClientId: '1074170874944-cjr6fv1tf6b44uabaenidcjjfkvklv44.apps.googleusercontent.com',
    iosBundleId: 'com.example.realcapstone',
  );
}
